/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.vez.kvstore;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainAppTest {
    @Test public void appHasAGreeting() {
        MainApp classUnderTest = new MainApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
